### ISSUE TITLE
Sammler: Verschiedene Verbesserungsvorschläge

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1253]
- [x]  Orga-Breadcrumb: Abstände
- [x]  Breadcrumbs-Nav: Schmaler, im Wrapper, Abstände, u.a. in #1212 
- [x]  Buttons, Rahmen, Elemente: Designsprache vereinheitlichen; wenn abgerundete Ecken, dann überall. u.a. auch #1219,  #1207
- [x] #1260
- [x]  Icons: viele verschiedene Stile; Vereinheitlichung wäre gut, auch mehr an den restlichen Stil angepasst. siehe auch dazu: #730, #902,  #1221
- [x] Social-Media-Icons als Link: Hier auch mehr an Stil anpassen, etwas prominenter darstellen; eher als Button
- [x] Blogroll: Elemente wirken etwas lose; hier könnte man mehr Struktur einbauen. Datum und Kategorien stärker vom Rest abheben, „Weiterlesen“-Button abtrennen vom Thumbnail und Excerpt
- [x] #1347
- [x] Maximale Textbreite bei Content prüfen und ggf. anpassen (70ch ?)
- [x] #1291 (wird von FAU Team selbst gemacht)
- [x]  Bildergalerie Slider: numerische Selektoren zentrieren, eher als rechteckige Buttons gestalten: Dies aber noch abstimmen. (Vorschlag entwerfen)
- [x]  Pagination: Kein Unterstrich bei Hover
- [x]  Content Menu: Redesign. MIt Vorschlag. Auch Zusammenhang zu Issues des Portalmenüs in 2.3
- [x]  #1252 . u.a Sticky Header: Nimmt sehr viel Platz ein – man könnte ihn beim Herunterscrollen ausblenden, um ihn dann nur beim Hochscrollen anzuzeigen, Option anbieten im Customizer. Vgl. auch:

**Comment by xwolfde** [comment]
Hinweis zu den Bildergalerie Slider, nimmerische Selektoren: Es gibt bereits ein Pagination:
<img width="739" alt="grafik" src="https://user-images.githubusercontent.com/1070669/229108666-515e0175-93c5-4997-9c0b-a7219215fcbb.png">

Wäre das so gedacht? Aber prüfen, ob das zu BIlder passt.

**Comment by xwolfde** [comment]
Der Punkt
" Customizer: Neusortieren für besseren Workflow – nicht intuitiv für neue User"
wird erstmal rausgenommen, da dies aktuell zu viel Ändeurngen in der Dokumentation und Neulernen der bestandsuser erfordern würde, die aktuell nicht geleistet werden kann.

**Comment by xwolfde** [comment]
Zu dem Punkt hinsichtlich der Bildergalerie gibt es auch ein anhängiges Problem: #1318
