### ISSUE TITLE
coer-Blocks Todo-List

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Einrichtungen#1470]
(AZusammenfassung von Lukas aus der Diskussion #1446  übernommen):

### Text
- [ ] core/paragraph (spacing und background presets)
- [ ] core/heading
- [ ] core /list
- [ ] core/pullquote
- [ ] core/quote (Alignments / Background)
- [ ] core/table #1468 
- [ ] core/details
- [ ] core/verse
- [ ] core/latest-posts
- [ ] core/columns
- [ ] core/cover

### Medien
- [ ] core/image #1381 (figure.align => width: 100vw; entfernen)
- [ ] core/gallery
- [ ] (core/audio)
- [ ] core/cover
- [ ] (core/file)
- [ ] core/media-text

### Design
- [ ] core/buttons (styling inkl. rounded, outline, square Option über theme.json entfernen)
- [ ] core/columns
- [ ] core/group
- [ ] (core/stack)
- [ ] core/divider
- [ ] (core/row)

### Widgets
- [ ] core/latest-posts
- [ ] core/archives
- [ ] core/categories
- [ ] core/tag-cloud
- [ ] core/social-links

### Sonstige
- [ ] Loop/Blogroll
